### ISSUE TITLE
Allow -n option for gzip

### ISSUE THREAD

**Issue by ferrybig** [StefH/ghaction-CompressFiles#2]
At the moment, this Github Action calls gzip without the -n flag. This means every build produces a new file that checksums to a different checksum.

When deploying your application, you normally could use rsync --checksum flag to deal with the file modification times changing. However, since the produced gzipped files also change their checksum, it means they always gets redeployed, which means in turn the users of the webserver see the file as modified and have to download it again, even though it represents the same resource.

gzip has a flag -n for this, which does not record the original files modification date inside the gzipped archieve, which is designed for determistic builds. At the moment, this Github Action does not have a way to pass custom flags to the gzip command, so it cannot be used.

**Comment by StefH** [comment]
Can you make a PR to add a this new option?

**Comment by ferrybig** [comment]
I'm not sure about all the steps required for this.

So far I have tried: https://github.com/ferrybig/ghaction-CompressFiles/commit/7339a0a46b8555f8e0e21dd371c97835cbc417a1

After trying out my own fork in a github actions project, it still did not pick it up as `action.yml` still specified your published docker container.

One thing to keep in mind, is that no version is specified in `action.yml`, so if you publish a new version of the inner docker container, everyone will upgrade to the never version, even if they pinned the version, they automatically upgrade. *This is the point I'm not sure how to solve in the current state*

**Comment by StefH** [comment]
As far as I can remember... (It's about 2 years since I created this project)

The version is also defined in the docker image.

See also this:
https://github.com/StefH/ghaction-BlazorWebAssemblyFileHashFixer/blob/master/create_how_to.md

I'll try to add the `-n` option.
- What be a good parameter name ? `noname` ?

**Comment by ferrybig** [comment]
I think a better name would be `deterministic` or `deterministicCompression`. 

The purpose of passing `-n` or `--noname` is make the output file exactly the same, _if_ the input file and the gzip versions are the same, no matter when you build the project. (without the flag, the original modification timestamp and original filename also affect the output)

**Comment by StefH** [comment]
@ferrybig 
I did try to fix it.

Can you test if version `v2` works fine?

**Comment by ferrybig** [comment]
Confirmed solved.

Running `file <one of the files>.gz` now no longer shows a timestamp.

Thank you for your time and effort, I appreciate it.
